### ISSUE TITLE
有办法不让css直接显示在源码中，而是分隔成css文件吗，这样不利于SEO

### ISSUE THREAD

**Issue by 11003** [markthree/nuxt-antd-css-demo#1]

**Comment by markthree** [comment]
@11003 请添加多一个模块 [nuxt-style-extractor](https://github.com/markthree/nuxt-style-extractor)

**Comment by markthree** [comment]
@11003 可以试试添加 [nuxt-style-extractor](https://github.com/markthree/nuxt-style-extractor) 模块
